// Code generated by MockGen. DO NOT EDIT.
// Source: akariUser.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=akariUser.go -destination=mock/akariUser.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAkariUserInteractor is a mock of AkariUserInteractor interface.
type MockAkariUserInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockAkariUserInteractorMockRecorder
	isgomock struct{}
}

// MockAkariUserInteractorMockRecorder is the mock recorder for MockAkariUserInteractor.
type MockAkariUserInteractorMockRecorder struct {
	mock *MockAkariUserInteractor
}

// NewMockAkariUserInteractor creates a new mock instance.
func NewMockAkariUserInteractor(ctrl *gomock.Controller) *MockAkariUserInteractor {
	mock := &MockAkariUserInteractor{ctrl: ctrl}
	mock.recorder = &MockAkariUserInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAkariUserInteractor) EXPECT() *MockAkariUserInteractorMockRecorder {
	return m.recorder
}

// CreateAkariUser mocks base method.
func (m *MockAkariUserInteractor) CreateAkariUser(ctx context.Context) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAkariUser", ctx)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAkariUser indicates an expected call of CreateAkariUser.
func (mr *MockAkariUserInteractorMockRecorder) CreateAkariUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAkariUser", reflect.TypeOf((*MockAkariUserInteractor)(nil).CreateAkariUser), ctx)
}

// DeleteAkariUser mocks base method.
func (m *MockAkariUserInteractor) DeleteAkariUser(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAkariUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAkariUser indicates an expected call of DeleteAkariUser.
func (mr *MockAkariUserInteractorMockRecorder) DeleteAkariUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAkariUser", reflect.TypeOf((*MockAkariUserInteractor)(nil).DeleteAkariUser), ctx, id)
}

// GetAkariUserByDiscordUserID mocks base method.
func (m *MockAkariUserInteractor) GetAkariUserByDiscordUserID(ctx context.Context, discordUserID string) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAkariUserByDiscordUserID", ctx, discordUserID)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAkariUserByDiscordUserID indicates an expected call of GetAkariUserByDiscordUserID.
func (mr *MockAkariUserInteractorMockRecorder) GetAkariUserByDiscordUserID(ctx, discordUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAkariUserByDiscordUserID", reflect.TypeOf((*MockAkariUserInteractor)(nil).GetAkariUserByDiscordUserID), ctx, discordUserID)
}

// GetAkariUserByID mocks base method.
func (m *MockAkariUserInteractor) GetAkariUserByID(ctx context.Context, id int) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAkariUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAkariUserByID indicates an expected call of GetAkariUserByID.
func (mr *MockAkariUserInteractorMockRecorder) GetAkariUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAkariUserByID", reflect.TypeOf((*MockAkariUserInteractor)(nil).GetAkariUserByID), ctx, id)
}

// ListAkariUsers mocks base method.
func (m *MockAkariUserInteractor) ListAkariUsers(ctx context.Context) ([]*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAkariUsers", ctx)
	ret0, _ := ret[0].([]*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAkariUsers indicates an expected call of ListAkariUsers.
func (mr *MockAkariUserInteractorMockRecorder) ListAkariUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAkariUsers", reflect.TypeOf((*MockAkariUserInteractor)(nil).ListAkariUsers), ctx)
}
