// Code generated by MockGen. DO NOT EDIT.
// Source: character.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=character.go -destination=mock/character.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterInteractor is a mock of CharacterInteractor interface.
type MockCharacterInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterInteractorMockRecorder
	isgomock struct{}
}

// MockCharacterInteractorMockRecorder is the mock recorder for MockCharacterInteractor.
type MockCharacterInteractorMockRecorder struct {
	mock *MockCharacterInteractor
}

// NewMockCharacterInteractor creates a new mock instance.
func NewMockCharacterInteractor(ctrl *gomock.Controller) *MockCharacterInteractor {
	mock := &MockCharacterInteractor{ctrl: ctrl}
	mock.recorder = &MockCharacterInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterInteractor) EXPECT() *MockCharacterInteractorMockRecorder {
	return m.recorder
}

// GetCharacterByID mocks base method.
func (m *MockCharacterInteractor) GetCharacterByID(ctx context.Context, characterID int) (*domain.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByID", ctx, characterID)
	ret0, _ := ret[0].(*domain.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByID indicates an expected call of GetCharacterByID.
func (mr *MockCharacterInteractorMockRecorder) GetCharacterByID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByID", reflect.TypeOf((*MockCharacterInteractor)(nil).GetCharacterByID), ctx, characterID)
}

// ListCharacters mocks base method.
func (m *MockCharacterInteractor) ListCharacters(ctx context.Context) ([]*domain.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCharacters", ctx)
	ret0, _ := ret[0].([]*domain.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharacters indicates an expected call of ListCharacters.
func (mr *MockCharacterInteractorMockRecorder) ListCharacters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharacters", reflect.TypeOf((*MockCharacterInteractor)(nil).ListCharacters), ctx)
}
