// Code generated by MockGen. DO NOT EDIT.
// Source: conversation.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=conversation.go -destination=mock/conversation.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationInteractor is a mock of ConversationInteractor interface.
type MockConversationInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockConversationInteractorMockRecorder
	isgomock struct{}
}

// MockConversationInteractorMockRecorder is the mock recorder for MockConversationInteractor.
type MockConversationInteractorMockRecorder struct {
	mock *MockConversationInteractor
}

// NewMockConversationInteractor creates a new mock instance.
func NewMockConversationInteractor(ctrl *gomock.Controller) *MockConversationInteractor {
	mock := &MockConversationInteractor{ctrl: ctrl}
	mock.recorder = &MockConversationInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationInteractor) EXPECT() *MockConversationInteractorMockRecorder {
	return m.recorder
}

// CreateConversation mocks base method.
func (m *MockConversationInteractor) CreateConversation(ctx context.Context, messageID string, userID int, conversationGroupID *int) (*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, messageID, userID, conversationGroupID)
	ret0, _ := ret[0].(*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockConversationInteractorMockRecorder) CreateConversation(ctx, messageID, userID, conversationGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockConversationInteractor)(nil).CreateConversation), ctx, messageID, userID, conversationGroupID)
}

// DeleteConversation mocks base method.
func (m *MockConversationInteractor) DeleteConversation(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversation indicates an expected call of DeleteConversation.
func (mr *MockConversationInteractorMockRecorder) DeleteConversation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversation", reflect.TypeOf((*MockConversationInteractor)(nil).DeleteConversation), ctx, id)
}

// GetConversationByID mocks base method.
func (m *MockConversationInteractor) GetConversationByID(ctx context.Context, id int) (*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationByID", ctx, id)
	ret0, _ := ret[0].(*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationByID indicates an expected call of GetConversationByID.
func (mr *MockConversationInteractorMockRecorder) GetConversationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationByID", reflect.TypeOf((*MockConversationInteractor)(nil).GetConversationByID), ctx, id)
}

// ListConversations mocks base method.
func (m *MockConversationInteractor) ListConversations(ctx context.Context) ([]*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx)
	ret0, _ := ret[0].([]*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockConversationInteractorMockRecorder) ListConversations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockConversationInteractor)(nil).ListConversations), ctx)
}
