// Code generated by MockGen. DO NOT EDIT.
// Source: conversationGroup.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=conversationGroup.go -destination=mock/conversationGroup.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationGroupInteractor is a mock of ConversationGroupInteractor interface.
type MockConversationGroupInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockConversationGroupInteractorMockRecorder
	isgomock struct{}
}

// MockConversationGroupInteractorMockRecorder is the mock recorder for MockConversationGroupInteractor.
type MockConversationGroupInteractorMockRecorder struct {
	mock *MockConversationGroupInteractor
}

// NewMockConversationGroupInteractor creates a new mock instance.
func NewMockConversationGroupInteractor(ctrl *gomock.Controller) *MockConversationGroupInteractor {
	mock := &MockConversationGroupInteractor{ctrl: ctrl}
	mock.recorder = &MockConversationGroupInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationGroupInteractor) EXPECT() *MockConversationGroupInteractorMockRecorder {
	return m.recorder
}

// CreateConversationGroup mocks base method.
func (m *MockConversationGroupInteractor) CreateConversationGroup(ctx context.Context, characterID int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversationGroup", ctx, characterID)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversationGroup indicates an expected call of CreateConversationGroup.
func (mr *MockConversationGroupInteractorMockRecorder) CreateConversationGroup(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversationGroup", reflect.TypeOf((*MockConversationGroupInteractor)(nil).CreateConversationGroup), ctx, characterID)
}

// DeleteConversationGroup mocks base method.
func (m *MockConversationGroupInteractor) DeleteConversationGroup(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversationGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversationGroup indicates an expected call of DeleteConversationGroup.
func (mr *MockConversationGroupInteractorMockRecorder) DeleteConversationGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversationGroup", reflect.TypeOf((*MockConversationGroupInteractor)(nil).DeleteConversationGroup), ctx, id)
}

// GetConversationGroupByCharacterID mocks base method.
func (m *MockConversationGroupInteractor) GetConversationGroupByCharacterID(ctx context.Context, characterID int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationGroupByCharacterID", ctx, characterID)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationGroupByCharacterID indicates an expected call of GetConversationGroupByCharacterID.
func (mr *MockConversationGroupInteractorMockRecorder) GetConversationGroupByCharacterID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationGroupByCharacterID", reflect.TypeOf((*MockConversationGroupInteractor)(nil).GetConversationGroupByCharacterID), ctx, characterID)
}

// GetConversationGroupByID mocks base method.
func (m *MockConversationGroupInteractor) GetConversationGroupByID(ctx context.Context, id int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationGroupByID", ctx, id)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationGroupByID indicates an expected call of GetConversationGroupByID.
func (mr *MockConversationGroupInteractorMockRecorder) GetConversationGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationGroupByID", reflect.TypeOf((*MockConversationGroupInteractor)(nil).GetConversationGroupByID), ctx, id)
}

// ListConversationGroups mocks base method.
func (m *MockConversationGroupInteractor) ListConversationGroups(ctx context.Context) ([]*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversationGroups", ctx)
	ret0, _ := ret[0].([]*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversationGroups indicates an expected call of ListConversationGroups.
func (mr *MockConversationGroupInteractorMockRecorder) ListConversationGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversationGroups", reflect.TypeOf((*MockConversationGroupInteractor)(nil).ListConversationGroups), ctx)
}
