// Code generated by MockGen. DO NOT EDIT.
// Source: discordChannel.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordChannel.go -destination=mock/discordChannel.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordChannelInteractor is a mock of DiscordChannelInteractor interface.
type MockDiscordChannelInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordChannelInteractorMockRecorder
	isgomock struct{}
}

// MockDiscordChannelInteractorMockRecorder is the mock recorder for MockDiscordChannelInteractor.
type MockDiscordChannelInteractorMockRecorder struct {
	mock *MockDiscordChannelInteractor
}

// NewMockDiscordChannelInteractor creates a new mock instance.
func NewMockDiscordChannelInteractor(ctrl *gomock.Controller) *MockDiscordChannelInteractor {
	mock := &MockDiscordChannelInteractor{ctrl: ctrl}
	mock.recorder = &MockDiscordChannelInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordChannelInteractor) EXPECT() *MockDiscordChannelInteractorMockRecorder {
	return m.recorder
}

// CreateDiscordChannel mocks base method.
func (m *MockDiscordChannelInteractor) CreateDiscordChannel(ctx context.Context, params domain.DiscordChannel) (*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordChannel", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordChannel indicates an expected call of CreateDiscordChannel.
func (mr *MockDiscordChannelInteractorMockRecorder) CreateDiscordChannel(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordChannel", reflect.TypeOf((*MockDiscordChannelInteractor)(nil).CreateDiscordChannel), ctx, params)
}

// DeleteDiscordChannel mocks base method.
func (m *MockDiscordChannelInteractor) DeleteDiscordChannel(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordChannel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordChannel indicates an expected call of DeleteDiscordChannel.
func (mr *MockDiscordChannelInteractorMockRecorder) DeleteDiscordChannel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordChannel", reflect.TypeOf((*MockDiscordChannelInteractor)(nil).DeleteDiscordChannel), ctx, id)
}

// GetDiscordChannelByID mocks base method.
func (m *MockDiscordChannelInteractor) GetDiscordChannelByID(ctx context.Context, channelID string) (*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordChannelByID", ctx, channelID)
	ret0, _ := ret[0].(*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordChannelByID indicates an expected call of GetDiscordChannelByID.
func (mr *MockDiscordChannelInteractorMockRecorder) GetDiscordChannelByID(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordChannelByID", reflect.TypeOf((*MockDiscordChannelInteractor)(nil).GetDiscordChannelByID), ctx, channelID)
}

// GetDiscordChannelByMessageID mocks base method.
func (m *MockDiscordChannelInteractor) GetDiscordChannelByMessageID(ctx context.Context, messageID string) (*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordChannelByMessageID", ctx, messageID)
	ret0, _ := ret[0].(*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordChannelByMessageID indicates an expected call of GetDiscordChannelByMessageID.
func (mr *MockDiscordChannelInteractorMockRecorder) GetDiscordChannelByMessageID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordChannelByMessageID", reflect.TypeOf((*MockDiscordChannelInteractor)(nil).GetDiscordChannelByMessageID), ctx, messageID)
}

// GetDiscordChannelsByGuildID mocks base method.
func (m *MockDiscordChannelInteractor) GetDiscordChannelsByGuildID(ctx context.Context, guildID string) ([]*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordChannelsByGuildID", ctx, guildID)
	ret0, _ := ret[0].([]*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordChannelsByGuildID indicates an expected call of GetDiscordChannelsByGuildID.
func (mr *MockDiscordChannelInteractorMockRecorder) GetDiscordChannelsByGuildID(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordChannelsByGuildID", reflect.TypeOf((*MockDiscordChannelInteractor)(nil).GetDiscordChannelsByGuildID), ctx, guildID)
}
