// Code generated by MockGen. DO NOT EDIT.
// Source: discordMessage.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordMessage.go -destination=mock/discordMessage.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordMessageInteractor is a mock of DiscordMessageInteractor interface.
type MockDiscordMessageInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordMessageInteractorMockRecorder
	isgomock struct{}
}

// MockDiscordMessageInteractorMockRecorder is the mock recorder for MockDiscordMessageInteractor.
type MockDiscordMessageInteractorMockRecorder struct {
	mock *MockDiscordMessageInteractor
}

// NewMockDiscordMessageInteractor creates a new mock instance.
func NewMockDiscordMessageInteractor(ctrl *gomock.Controller) *MockDiscordMessageInteractor {
	mock := &MockDiscordMessageInteractor{ctrl: ctrl}
	mock.recorder = &MockDiscordMessageInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordMessageInteractor) EXPECT() *MockDiscordMessageInteractorMockRecorder {
	return m.recorder
}

// CreateDiscordMessage mocks base method.
func (m *MockDiscordMessageInteractor) CreateDiscordMessage(ctx context.Context, params domain.DiscordMessage) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordMessage", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordMessage indicates an expected call of CreateDiscordMessage.
func (mr *MockDiscordMessageInteractorMockRecorder) CreateDiscordMessage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordMessage", reflect.TypeOf((*MockDiscordMessageInteractor)(nil).CreateDiscordMessage), ctx, params)
}

// DeleteDiscordMessage mocks base method.
func (m *MockDiscordMessageInteractor) DeleteDiscordMessage(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordMessage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordMessage indicates an expected call of DeleteDiscordMessage.
func (mr *MockDiscordMessageInteractorMockRecorder) DeleteDiscordMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordMessage", reflect.TypeOf((*MockDiscordMessageInteractor)(nil).DeleteDiscordMessage), ctx, id)
}

// GetDiscordMessageByID mocks base method.
func (m *MockDiscordMessageInteractor) GetDiscordMessageByID(ctx context.Context, messageID string) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordMessageByID", ctx, messageID)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordMessageByID indicates an expected call of GetDiscordMessageByID.
func (mr *MockDiscordMessageInteractorMockRecorder) GetDiscordMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordMessageByID", reflect.TypeOf((*MockDiscordMessageInteractor)(nil).GetDiscordMessageByID), ctx, messageID)
}
