// Code generated by MockGen. DO NOT EDIT.
// Source: discordGuild.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordGuild.go -destination=mock/discordGuild.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordGuildInteractor is a mock of DiscordGuildInteractor interface.
type MockDiscordGuildInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordGuildInteractorMockRecorder
	isgomock struct{}
}

// MockDiscordGuildInteractorMockRecorder is the mock recorder for MockDiscordGuildInteractor.
type MockDiscordGuildInteractorMockRecorder struct {
	mock *MockDiscordGuildInteractor
}

// NewMockDiscordGuildInteractor creates a new mock instance.
func NewMockDiscordGuildInteractor(ctrl *gomock.Controller) *MockDiscordGuildInteractor {
	mock := &MockDiscordGuildInteractor{ctrl: ctrl}
	mock.recorder = &MockDiscordGuildInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordGuildInteractor) EXPECT() *MockDiscordGuildInteractorMockRecorder {
	return m.recorder
}

// CreateDiscordGuild mocks base method.
func (m *MockDiscordGuildInteractor) CreateDiscordGuild(ctx context.Context, params domain.DiscordGuild) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordGuild", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordGuild indicates an expected call of CreateDiscordGuild.
func (mr *MockDiscordGuildInteractorMockRecorder) CreateDiscordGuild(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordGuild", reflect.TypeOf((*MockDiscordGuildInteractor)(nil).CreateDiscordGuild), ctx, params)
}

// DeleteDiscordGuild mocks base method.
func (m *MockDiscordGuildInteractor) DeleteDiscordGuild(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordGuild", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordGuild indicates an expected call of DeleteDiscordGuild.
func (mr *MockDiscordGuildInteractorMockRecorder) DeleteDiscordGuild(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordGuild", reflect.TypeOf((*MockDiscordGuildInteractor)(nil).DeleteDiscordGuild), ctx, id)
}

// GetDiscordGuildByChannelID mocks base method.
func (m *MockDiscordGuildInteractor) GetDiscordGuildByChannelID(ctx context.Context, channelID string) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordGuildByChannelID", ctx, channelID)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordGuildByChannelID indicates an expected call of GetDiscordGuildByChannelID.
func (mr *MockDiscordGuildInteractorMockRecorder) GetDiscordGuildByChannelID(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordGuildByChannelID", reflect.TypeOf((*MockDiscordGuildInteractor)(nil).GetDiscordGuildByChannelID), ctx, channelID)
}

// GetDiscordGuildByID mocks base method.
func (m *MockDiscordGuildInteractor) GetDiscordGuildByID(ctx context.Context, guildID string) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordGuildByID", ctx, guildID)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordGuildByID indicates an expected call of GetDiscordGuildByID.
func (mr *MockDiscordGuildInteractorMockRecorder) GetDiscordGuildByID(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordGuildByID", reflect.TypeOf((*MockDiscordGuildInteractor)(nil).GetDiscordGuildByID), ctx, guildID)
}

// ListDiscordGuilds mocks base method.
func (m *MockDiscordGuildInteractor) ListDiscordGuilds(ctx context.Context) ([]*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordGuilds", ctx)
	ret0, _ := ret[0].([]*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordGuilds indicates an expected call of ListDiscordGuilds.
func (mr *MockDiscordGuildInteractorMockRecorder) ListDiscordGuilds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordGuilds", reflect.TypeOf((*MockDiscordGuildInteractor)(nil).ListDiscordGuilds), ctx)
}
