// Code generated by MockGen. DO NOT EDIT.
// Source: discordUser.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordUser.go -destination=mock/discordUser.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordUserInteractor is a mock of DiscordUserInteractor interface.
type MockDiscordUserInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordUserInteractorMockRecorder
	isgomock struct{}
}

// MockDiscordUserInteractorMockRecorder is the mock recorder for MockDiscordUserInteractor.
type MockDiscordUserInteractorMockRecorder struct {
	mock *MockDiscordUserInteractor
}

// NewMockDiscordUserInteractor creates a new mock instance.
func NewMockDiscordUserInteractor(ctrl *gomock.Controller) *MockDiscordUserInteractor {
	mock := &MockDiscordUserInteractor{ctrl: ctrl}
	mock.recorder = &MockDiscordUserInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordUserInteractor) EXPECT() *MockDiscordUserInteractorMockRecorder {
	return m.recorder
}

// CreateDiscordUser mocks base method.
func (m *MockDiscordUserInteractor) CreateDiscordUser(ctx context.Context, params domain.DiscordUser) (*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordUser", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordUser indicates an expected call of CreateDiscordUser.
func (mr *MockDiscordUserInteractorMockRecorder) CreateDiscordUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordUser", reflect.TypeOf((*MockDiscordUserInteractor)(nil).CreateDiscordUser), ctx, params)
}

// DeleteDiscordUser mocks base method.
func (m *MockDiscordUserInteractor) DeleteDiscordUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordUser indicates an expected call of DeleteDiscordUser.
func (mr *MockDiscordUserInteractorMockRecorder) DeleteDiscordUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordUser", reflect.TypeOf((*MockDiscordUserInteractor)(nil).DeleteDiscordUser), ctx, userID)
}

// GetDiscordUserByID mocks base method.
func (m *MockDiscordUserInteractor) GetDiscordUserByID(ctx context.Context, userID string) (*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordUserByID indicates an expected call of GetDiscordUserByID.
func (mr *MockDiscordUserInteractorMockRecorder) GetDiscordUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordUserByID", reflect.TypeOf((*MockDiscordUserInteractor)(nil).GetDiscordUserByID), ctx, userID)
}

// ListDiscordUsers mocks base method.
func (m *MockDiscordUserInteractor) ListDiscordUsers(ctx context.Context) ([]*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordUsers", ctx)
	ret0, _ := ret[0].([]*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordUsers indicates an expected call of ListDiscordUsers.
func (mr *MockDiscordUserInteractorMockRecorder) ListDiscordUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordUsers", reflect.TypeOf((*MockDiscordUserInteractor)(nil).ListDiscordUsers), ctx)
}
