// Code generated by MockGen. DO NOT EDIT.
// Source: systemPrompt.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=systemPrompt.go -destination=mock/systemPrompt.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemPromptInteractor is a mock of SystemPromptInteractor interface.
type MockSystemPromptInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockSystemPromptInteractorMockRecorder
	isgomock struct{}
}

// MockSystemPromptInteractorMockRecorder is the mock recorder for MockSystemPromptInteractor.
type MockSystemPromptInteractorMockRecorder struct {
	mock *MockSystemPromptInteractor
}

// NewMockSystemPromptInteractor creates a new mock instance.
func NewMockSystemPromptInteractor(ctrl *gomock.Controller) *MockSystemPromptInteractor {
	mock := &MockSystemPromptInteractor{ctrl: ctrl}
	mock.recorder = &MockSystemPromptInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemPromptInteractor) EXPECT() *MockSystemPromptInteractorMockRecorder {
	return m.recorder
}

// GetSystemPromptByID mocks base method.
func (m *MockSystemPromptInteractor) GetSystemPromptByID(ctx context.Context, id int) (*domain.SystemPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPromptByID", ctx, id)
	ret0, _ := ret[0].(*domain.SystemPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPromptByID indicates an expected call of GetSystemPromptByID.
func (mr *MockSystemPromptInteractorMockRecorder) GetSystemPromptByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPromptByID", reflect.TypeOf((*MockSystemPromptInteractor)(nil).GetSystemPromptByID), ctx, id)
}
