// Code generated by MockGen. DO NOT EDIT.
// Source: discord.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discord.go -destination=mock/discord.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordService is a mock of DiscordService interface.
type MockDiscordService struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordServiceMockRecorder
	isgomock struct{}
}

// MockDiscordServiceMockRecorder is the mock recorder for MockDiscordService.
type MockDiscordServiceMockRecorder struct {
	mock *MockDiscordService
}

// NewMockDiscordService creates a new mock instance.
func NewMockDiscordService(ctrl *gomock.Controller) *MockDiscordService {
	mock := &MockDiscordService{ctrl: ctrl}
	mock.recorder = &MockDiscordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordService) EXPECT() *MockDiscordServiceMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockDiscordService) GetMessage(ctx context.Context, channelID, messageID string) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, channelID, messageID)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockDiscordServiceMockRecorder) GetMessage(ctx, channelID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockDiscordService)(nil).GetMessage), ctx, channelID, messageID)
}

// SendMessage mocks base method.
func (m *MockDiscordService) SendMessage(ctx context.Context, channelID, content string) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordServiceMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordService)(nil).SendMessage), ctx, channelID, content)
}
