// Code generated by MockGen. DO NOT EDIT.
// Source: llm.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=llm.go -destination=mock/llm.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/llm/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMInteractor is a mock of LLMInteractor interface.
type MockLLMInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockLLMInteractorMockRecorder
	isgomock struct{}
}

// MockLLMInteractorMockRecorder is the mock recorder for MockLLMInteractor.
type MockLLMInteractorMockRecorder struct {
	mock *MockLLMInteractor
}

// NewMockLLMInteractor creates a new mock instance.
func NewMockLLMInteractor(ctrl *gomock.Controller) *MockLLMInteractor {
	mock := &MockLLMInteractor{ctrl: ctrl}
	mock.recorder = &MockLLMInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMInteractor) EXPECT() *MockLLMInteractorMockRecorder {
	return m.recorder
}

// SendChatMessage mocks base method.
func (m *MockLLMInteractor) SendChatMessage(ctx context.Context, systemPrompt string, history []*domain.Content, message string, functions []domain.Function) ([]*string, []*domain.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChatMessage", ctx, systemPrompt, history, message, functions)
	ret0, _ := ret[0].([]*string)
	ret1, _ := ret[1].([]*domain.Part)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendChatMessage indicates an expected call of SendChatMessage.
func (mr *MockLLMInteractorMockRecorder) SendChatMessage(ctx, systemPrompt, history, message, functions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChatMessage", reflect.TypeOf((*MockLLMInteractor)(nil).SendChatMessage), ctx, systemPrompt, history, message, functions)
}
