// Code generated by MockGen. DO NOT EDIT.
// Source: handleMessage.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=handleMessage.go -destination=mock/handleMessage.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/kizuna-org/akari/pkg/discord/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockHandleMessageInteractor is a mock of HandleMessageInteractor interface.
type MockHandleMessageInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockHandleMessageInteractorMockRecorder
	isgomock struct{}
}

// MockHandleMessageInteractorMockRecorder is the mock recorder for MockHandleMessageInteractor.
type MockHandleMessageInteractorMockRecorder struct {
	mock *MockHandleMessageInteractor
}

// NewMockHandleMessageInteractor creates a new mock instance.
func NewMockHandleMessageInteractor(ctrl *gomock.Controller) *MockHandleMessageInteractor {
	mock := &MockHandleMessageInteractor{ctrl: ctrl}
	mock.recorder = &MockHandleMessageInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandleMessageInteractor) EXPECT() *MockHandleMessageInteractorMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockHandleMessageInteractor) Handle(ctx context.Context, user *entity.User, message *entity.Message, channel *entity.Channel, guild *entity.Guild) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, user, message, channel, guild)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockHandleMessageInteractorMockRecorder) Handle(ctx, user, message, channel, guild any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHandleMessageInteractor)(nil).Handle), ctx, user, message, channel, guild)
}

// SetBotUserID mocks base method.
func (m *MockHandleMessageInteractor) SetBotUserID(botUserID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBotUserID", botUserID)
}

// SetBotUserID indicates an expected call of SetBotUserID.
func (mr *MockHandleMessageInteractorMockRecorder) SetBotUserID(botUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotUserID", reflect.TypeOf((*MockHandleMessageInteractor)(nil).SetBotUserID), botUserID)
}
