name: Setup DB container
description: Setup DB container

inputs:
  working-directory:
    description: The working directory to run the commands in. Default is ./akari.
    required: false
    default: ./akari

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-golang
    - name: Run `make init`
      shell: bash
      working-directory: ${{ steps.get-current-directory.outputs.current-directory }}
      run: |
        make init
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Start DB container
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        docker compose build akari-db akari-db-side
        docker compose up -d --no-build akari-db akari-db-side
    - name: Run `make migrate-apply`
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        make migrate-apply
