name: Setup DB container
description: Setup DB container

inputs:
  working-directory:
    description: The working directory to run the commands in. Default is ./akari.
    required: false
    default: ./akari

runs:
  using: composite
  steps:
    - name: Check if Go is already set up
      id: check-go
      shell: bash
      run: |
        if command -v go >/dev/null 2>&1; then
          echo "go-already-setup=true" >> $GITHUB_OUTPUT
        else
          echo "go-already-setup=false" >> $GITHUB_OUTPUT
        fi
    - uses: ./.github/actions/setup-golang
      if: steps.check-go.outputs.go-already-setup != 'true'
      with:
        working-directory: ${{ inputs.working-directory }}
    - name: Run `make init`
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        make init
    - uses: ariga/setup-atlas@v0
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Start DB container
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        docker compose build akari-db akari-db-side
        docker compose up -d --no-build akari-db akari-db-side
    - name: Run `make migrate-apply`
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        make migrate-apply
