version: "2"
linters:
  default: all
  disable:
    - depguard
    - wrapcheck
    - ireturn
    - err113
    - shironerr113
  exclusions:
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - exhaustruct
          - funlen
      - path: ^go\.mod$
        linters:
          - gomoddirectives

  settings:
    custom:
      shironerr113:
        type: "module"
    revive:
      rules:
        - name: package-comments
          disabled: true
    varnamelen:
      ignore-decls:
        - i int
