services:
  akari-db:
    image: postgres:18.3@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    container_name: akari-db
    env_file: .env
    volumes:
      - db-store:/var/lib/pgsql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      TZ: UTC
  akari-db-side:
    image: alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    container_name: akari-db-side
    command: ["sh", "-c", "echo 'Wake up db-side'"]
    depends_on:
      akari-db:
        condition: service_healthy

volumes:
  db-store:
