FROM golang:1.26.2-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1 AS builder

WORKDIR /build

# renovate: datasource=repology packagePrefix=alpine_3_23 versioning=loose
RUN apk add --no-cache git=2.52.0-r0 make=4.4.1-r3

COPY akari/go.mod akari/go.sum ./
RUN go mod download

COPY akari/ .

RUN make generate

FROM arigaio/atlas:1.3.2@sha256:1e4fe2e242281555f8fc41a95f09b94ccd47f85ee3a6bc1e808e1e48d27e4b39

WORKDIR /app

COPY --from=builder /build /app

ENV TZ=UTC

CMD ["migrate", "apply", "--env=dev"]
