FROM golang:1.26.0-alpine@sha256:d4c4845f5d60c6a974c6000ce58ae079328d03ab7f721a0734277e69905473e5 AS builder

WORKDIR /build

RUN apk add --no-cache git=2.52.0-r0 make=4.4.1-r3

COPY akari/go.mod akari/go.sum ./
RUN go mod download

COPY akari/ .
COPY kiseki/openapi/openapi.yaml ../kiseki/openapi/openapi.yaml

RUN make generate

FROM arigaio/atlas:1.1.2@sha256:fd8b310942ebc1ecb03e903be18889b6e8ac5c8251bf664e4c6a0fa130cc4f4a

WORKDIR /app

COPY --from=builder /build /app

ENV TZ=UTC

CMD ["migrate", "apply", "--env=dev"]
