FROM golang:1.25.6-alpine@sha256:98e6cffc31ccc44c7c15d83df1d69891efee8115a5bb7ede2bf30a38af3e3c92 AS builder

WORKDIR /build

RUN apk add --no-cache git=2.52.0-r0 make=4.4.1-r3

COPY akari/go.mod akari/go.sum ./
RUN go mod download

COPY akari/ .
COPY kiseki/openapi/openapi.yaml ../kiseki/openapi/openapi.yaml

RUN make generate

FROM arigaio/atlas:1.0.0@sha256:0c5585e0768aeb500c1322e056caafe8a01c6cfc7cf2e5430ec26a6fc9541c09

WORKDIR /app

COPY --from=builder /build /app

ENV TZ=UTC

CMD ["migrate", "apply", "--env=dev"]
