// Code generated by MockGen. DO NOT EDIT.
// Source: discord.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discord.go -destination=mock/discord.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/kizuna-org/akari/pkg/discord/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordInteractor is a mock of DiscordInteractor interface.
type MockDiscordInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordInteractorMockRecorder
	isgomock struct{}
}

// MockDiscordInteractorMockRecorder is the mock recorder for MockDiscordInteractor.
type MockDiscordInteractorMockRecorder struct {
	mock *MockDiscordInteractor
}

// NewMockDiscordInteractor creates a new mock instance.
func NewMockDiscordInteractor(ctrl *gomock.Controller) *MockDiscordInteractor {
	mock := &MockDiscordInteractor{ctrl: ctrl}
	mock.recorder = &MockDiscordInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordInteractor) EXPECT() *MockDiscordInteractorMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockDiscordInteractor) GetMessage(ctx context.Context, channelID, messageID string) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, channelID, messageID)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockDiscordInteractorMockRecorder) GetMessage(ctx, channelID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockDiscordInteractor)(nil).GetMessage), ctx, channelID, messageID)
}

// SendMessage mocks base method.
func (m *MockDiscordInteractor) SendMessage(ctx context.Context, channelID, content string) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordInteractorMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordInteractor)(nil).SendMessage), ctx, channelID, content)
}
