-- Create "conversation_groups" table
CREATE TABLE "conversation_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "conversation_group_character" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversation_groups_characters_character" FOREIGN KEY ("conversation_group_character") REFERENCES "characters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "conversationgroup_created_at" to table: "conversation_groups"
CREATE INDEX "conversationgroup_created_at" ON "conversation_groups" ("created_at");
-- Create "conversations" table
CREATE TABLE "conversations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "conversation_group_conversations" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversations_conversation_groups_conversations" FOREIGN KEY ("conversation_group_conversations") REFERENCES "conversation_groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "conversation_created_at" to table: "conversations"
CREATE INDEX "conversation_created_at" ON "conversations" ("created_at");
-- Modify "discord_messages" table
ALTER TABLE "discord_messages" ADD COLUMN "conversation_discord_message" bigint NULL, ADD CONSTRAINT "discord_messages_conversations_discord_message" FOREIGN KEY ("conversation_discord_message") REFERENCES "conversations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "discord_messages_conversation_discord_message_key" to table: "discord_messages"
CREATE UNIQUE INDEX "discord_messages_conversation_discord_message_key" ON "discord_messages" ("conversation_discord_message");
