-- Create "characters" table
CREATE TABLE "characters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "character_system_prompt" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "characters_system_prompts_system_prompt" FOREIGN KEY ("character_system_prompt") REFERENCES "system_prompts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "characters_name_key" to table: "characters"
CREATE UNIQUE INDEX "characters_name_key" ON "characters" ("name");
