-- Create "akari_users" table
CREATE TABLE "akari_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Modify "conversations" table
ALTER TABLE "conversations" ADD COLUMN "conversation_user" bigint NOT NULL, ADD CONSTRAINT "conversations_akari_users_user" FOREIGN KEY ("conversation_user") REFERENCES "akari_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
