-- Create "conversation_groups" table
CREATE TABLE "conversation_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "conversationgroup_created_at" to table: "conversation_groups"
CREATE INDEX "conversationgroup_created_at" ON "conversation_groups" ("created_at");
-- Create "conversations" table
CREATE TABLE "conversations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "conversation_trigger_message" character varying NOT NULL,
  "conversation_response_message" character varying NOT NULL,
  "conversation_group_conversations" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversations_conversation_groups_conversations" FOREIGN KEY ("conversation_group_conversations") REFERENCES "conversation_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "conversations_discord_messages_response_message" FOREIGN KEY ("conversation_response_message") REFERENCES "discord_messages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "conversations_discord_messages_trigger_message" FOREIGN KEY ("conversation_trigger_message") REFERENCES "discord_messages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "conversation_created_at" to table: "conversations"
CREATE INDEX "conversation_created_at" ON "conversations" ("created_at");
