-- Create "character_configs" table
CREATE TABLE "character_configs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name_regexp" character varying NULL,
  "default_system_prompt" character varying NOT NULL,
  "character_config" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "character_configs_characters_config" FOREIGN KEY ("character_config") REFERENCES "characters" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "character_configs_character_config_key" to table: "character_configs"
CREATE UNIQUE INDEX "character_configs_character_config_key" ON "character_configs" ("character_config");
