// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=interface.go -destination=mock/interface.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	kiseki "github.com/kizuna-org/akari/gen/kiseki"
	domain "github.com/kizuna-org/akari/pkg/kiseki/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskHandler is a mock of TaskHandler interface.
type MockTaskHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHandlerMockRecorder
	isgomock struct{}
}

// MockTaskHandlerMockRecorder is the mock recorder for MockTaskHandler.
type MockTaskHandlerMockRecorder struct {
	mock *MockTaskHandler
}

// NewMockTaskHandler creates a new mock instance.
func NewMockTaskHandler(ctrl *gomock.Controller) *MockTaskHandler {
	mock := &MockTaskHandler{ctrl: ctrl}
	mock.recorder = &MockTaskHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskHandler) EXPECT() *MockTaskHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockTaskHandler) Handle(ctx context.Context, task *domain.PollingTask) (*domain.PollingTaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, task)
	ret0, _ := ret[0].(*domain.PollingTaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockTaskHandlerMockRecorder) Handle(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockTaskHandler)(nil).Handle), ctx, task)
}

// MockPollingService is a mock of PollingService interface.
type MockPollingService struct {
	ctrl     *gomock.Controller
	recorder *MockPollingServiceMockRecorder
	isgomock struct{}
}

// MockPollingServiceMockRecorder is the mock recorder for MockPollingService.
type MockPollingServiceMockRecorder struct {
	mock *MockPollingService
}

// NewMockPollingService creates a new mock instance.
func NewMockPollingService(ctrl *gomock.Controller) *MockPollingService {
	mock := &MockPollingService{ctrl: ctrl}
	mock.recorder = &MockPollingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollingService) EXPECT() *MockPollingServiceMockRecorder {
	return m.recorder
}

// IsRunning mocks base method.
func (m *MockPollingService) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockPollingServiceMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockPollingService)(nil).IsRunning))
}

// RegisterHandler mocks base method.
func (m *MockPollingService) RegisterHandler(taskType string, handler domain.TaskHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHandler", taskType, handler)
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockPollingServiceMockRecorder) RegisterHandler(taskType, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockPollingService)(nil).RegisterHandler), taskType, handler)
}

// Start mocks base method.
func (m *MockPollingService) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPollingServiceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPollingService)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockPollingService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockPollingServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPollingService)(nil).Stop))
}

// MockPollingClient is a mock of PollingClient interface.
type MockPollingClient struct {
	ctrl     *gomock.Controller
	recorder *MockPollingClientMockRecorder
	isgomock struct{}
}

// MockPollingClientMockRecorder is the mock recorder for MockPollingClient.
type MockPollingClientMockRecorder struct {
	mock *MockPollingClient
}

// NewMockPollingClient creates a new mock instance.
func NewMockPollingClient(ctrl *gomock.Controller) *MockPollingClient {
	mock := &MockPollingClient{ctrl: ctrl}
	mock.recorder = &MockPollingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollingClient) EXPECT() *MockPollingClientMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockPollingClient) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockPollingClientMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockPollingClient)(nil).HealthCheck), ctx)
}

// PostMemoryPolling mocks base method.
func (m *MockPollingClient) PostMemoryPolling(ctx context.Context, characterID string, request *kiseki.MemoryPollingRequest) (*kiseki.MemoryPollingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMemoryPolling", ctx, characterID, request)
	ret0, _ := ret[0].(*kiseki.MemoryPollingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostMemoryPolling indicates an expected call of PostMemoryPolling.
func (mr *MockPollingClientMockRecorder) PostMemoryPolling(ctx, characterID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMemoryPolling", reflect.TypeOf((*MockPollingClient)(nil).PostMemoryPolling), ctx, characterID, request)
}
