// Code generated by MockGen. DO NOT EDIT.
// Source: akariUser.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=akariUser.go -destination=mock/akariUser.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAkariUserRepository is a mock of AkariUserRepository interface.
type MockAkariUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAkariUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAkariUserRepositoryMockRecorder is the mock recorder for MockAkariUserRepository.
type MockAkariUserRepositoryMockRecorder struct {
	mock *MockAkariUserRepository
}

// NewMockAkariUserRepository creates a new mock instance.
func NewMockAkariUserRepository(ctrl *gomock.Controller) *MockAkariUserRepository {
	mock := &MockAkariUserRepository{ctrl: ctrl}
	mock.recorder = &MockAkariUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAkariUserRepository) EXPECT() *MockAkariUserRepositoryMockRecorder {
	return m.recorder
}

// CreateAkariUser mocks base method.
func (m *MockAkariUserRepository) CreateAkariUser(ctx context.Context, name string) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAkariUser", ctx, name)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAkariUser indicates an expected call of CreateAkariUser.
func (mr *MockAkariUserRepositoryMockRecorder) CreateAkariUser(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAkariUser", reflect.TypeOf((*MockAkariUserRepository)(nil).CreateAkariUser), ctx, name)
}

// DeleteAkariUser mocks base method.
func (m *MockAkariUserRepository) DeleteAkariUser(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAkariUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAkariUser indicates an expected call of DeleteAkariUser.
func (mr *MockAkariUserRepositoryMockRecorder) DeleteAkariUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAkariUser", reflect.TypeOf((*MockAkariUserRepository)(nil).DeleteAkariUser), ctx, id)
}

// GetAkariUserByID mocks base method.
func (m *MockAkariUserRepository) GetAkariUserByID(ctx context.Context, id int) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAkariUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAkariUserByID indicates an expected call of GetAkariUserByID.
func (mr *MockAkariUserRepositoryMockRecorder) GetAkariUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAkariUserByID", reflect.TypeOf((*MockAkariUserRepository)(nil).GetAkariUserByID), ctx, id)
}

// ListAkariUsers mocks base method.
func (m *MockAkariUserRepository) ListAkariUsers(ctx context.Context) ([]*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAkariUsers", ctx)
	ret0, _ := ret[0].([]*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAkariUsers indicates an expected call of ListAkariUsers.
func (mr *MockAkariUserRepositoryMockRecorder) ListAkariUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAkariUsers", reflect.TypeOf((*MockAkariUserRepository)(nil).ListAkariUsers), ctx)
}

// UpdateAkariUser mocks base method.
func (m *MockAkariUserRepository) UpdateAkariUser(ctx context.Context, id int, name string) (*domain.AkariUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAkariUser", ctx, id, name)
	ret0, _ := ret[0].(*domain.AkariUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAkariUser indicates an expected call of UpdateAkariUser.
func (mr *MockAkariUserRepositoryMockRecorder) UpdateAkariUser(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAkariUser", reflect.TypeOf((*MockAkariUserRepository)(nil).UpdateAkariUser), ctx, id, name)
}
