// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kizuna-org/akari/pkg/database/domain (interfaces: CharacterConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/database/domain/mock/characterConfig_mock.go -package=mock github.com/kizuna-org/akari/pkg/database/domain CharacterConfigRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterConfigRepository is a mock of CharacterConfigRepository interface.
type MockCharacterConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterConfigRepositoryMockRecorder is the mock recorder for MockCharacterConfigRepository.
type MockCharacterConfigRepositoryMockRecorder struct {
	mock *MockCharacterConfigRepository
}

// NewMockCharacterConfigRepository creates a new mock instance.
func NewMockCharacterConfigRepository(ctrl *gomock.Controller) *MockCharacterConfigRepository {
	mock := &MockCharacterConfigRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterConfigRepository) EXPECT() *MockCharacterConfigRepositoryMockRecorder {
	return m.recorder
}

// CreateCharacterConfig mocks base method.
func (m *MockCharacterConfigRepository) CreateCharacterConfig(ctx context.Context, characterID *int, nameRegexp *string, defaultSystemPrompt string) (*domain.CharacterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCharacterConfig", ctx, characterID, nameRegexp, defaultSystemPrompt)
	ret0, _ := ret[0].(*domain.CharacterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCharacterConfig indicates an expected call of CreateCharacterConfig.
func (mr *MockCharacterConfigRepositoryMockRecorder) CreateCharacterConfig(ctx, characterID, nameRegexp, defaultSystemPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCharacterConfig", reflect.TypeOf((*MockCharacterConfigRepository)(nil).CreateCharacterConfig), ctx, characterID, nameRegexp, defaultSystemPrompt)
}

// DeleteCharacterConfig mocks base method.
func (m *MockCharacterConfigRepository) DeleteCharacterConfig(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCharacterConfig", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCharacterConfig indicates an expected call of DeleteCharacterConfig.
func (mr *MockCharacterConfigRepositoryMockRecorder) DeleteCharacterConfig(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCharacterConfig", reflect.TypeOf((*MockCharacterConfigRepository)(nil).DeleteCharacterConfig), ctx, id)
}

// GetCharacterConfigByCharacterID mocks base method.
func (m *MockCharacterConfigRepository) GetCharacterConfigByCharacterID(ctx context.Context, characterID int) (*domain.CharacterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterConfigByCharacterID", ctx, characterID)
	ret0, _ := ret[0].(*domain.CharacterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterConfigByCharacterID indicates an expected call of GetCharacterConfigByCharacterID.
func (mr *MockCharacterConfigRepositoryMockRecorder) GetCharacterConfigByCharacterID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterConfigByCharacterID", reflect.TypeOf((*MockCharacterConfigRepository)(nil).GetCharacterConfigByCharacterID), ctx, characterID)
}

// GetCharacterConfigByID mocks base method.
func (m *MockCharacterConfigRepository) GetCharacterConfigByID(ctx context.Context, id int) (*domain.CharacterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterConfigByID", ctx, id)
	ret0, _ := ret[0].(*domain.CharacterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterConfigByID indicates an expected call of GetCharacterConfigByID.
func (mr *MockCharacterConfigRepositoryMockRecorder) GetCharacterConfigByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterConfigByID", reflect.TypeOf((*MockCharacterConfigRepository)(nil).GetCharacterConfigByID), ctx, id)
}

// UpdateCharacterConfig mocks base method.
func (m *MockCharacterConfigRepository) UpdateCharacterConfig(ctx context.Context, id int, characterID *int, nameRegexp, defaultSystemPrompt *string) (*domain.CharacterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCharacterConfig", ctx, id, characterID, nameRegexp, defaultSystemPrompt)
	ret0, _ := ret[0].(*domain.CharacterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCharacterConfig indicates an expected call of UpdateCharacterConfig.
func (mr *MockCharacterConfigRepositoryMockRecorder) UpdateCharacterConfig(ctx, id, characterID, nameRegexp, defaultSystemPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCharacterConfig", reflect.TypeOf((*MockCharacterConfigRepository)(nil).UpdateCharacterConfig), ctx, id, characterID, nameRegexp, defaultSystemPrompt)
}
