// Code generated by MockGen. DO NOT EDIT.
// Source: conversation.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=conversation.go -destination=mock/conversation.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationRepository is a mock of ConversationRepository interface.
type MockConversationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationRepositoryMockRecorder is the mock recorder for MockConversationRepository.
type MockConversationRepositoryMockRecorder struct {
	mock *MockConversationRepository
}

// NewMockConversationRepository creates a new mock instance.
func NewMockConversationRepository(ctrl *gomock.Controller) *MockConversationRepository {
	mock := &MockConversationRepository{ctrl: ctrl}
	mock.recorder = &MockConversationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepository) EXPECT() *MockConversationRepositoryMockRecorder {
	return m.recorder
}

// CreateConversation mocks base method.
func (m *MockConversationRepository) CreateConversation(ctx context.Context, params domain.Conversation) (*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, params)
	ret0, _ := ret[0].(*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockConversationRepositoryMockRecorder) CreateConversation(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockConversationRepository)(nil).CreateConversation), ctx, params)
}

// DeleteConversation mocks base method.
func (m *MockConversationRepository) DeleteConversation(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversation indicates an expected call of DeleteConversation.
func (mr *MockConversationRepositoryMockRecorder) DeleteConversation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversation", reflect.TypeOf((*MockConversationRepository)(nil).DeleteConversation), ctx, id)
}

// GetConversationByID mocks base method.
func (m *MockConversationRepository) GetConversationByID(ctx context.Context, id int) (*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationByID", ctx, id)
	ret0, _ := ret[0].(*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationByID indicates an expected call of GetConversationByID.
func (mr *MockConversationRepositoryMockRecorder) GetConversationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationByID", reflect.TypeOf((*MockConversationRepository)(nil).GetConversationByID), ctx, id)
}

// ListConversations mocks base method.
func (m *MockConversationRepository) ListConversations(ctx context.Context) ([]*domain.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx)
	ret0, _ := ret[0].([]*domain.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockConversationRepositoryMockRecorder) ListConversations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockConversationRepository)(nil).ListConversations), ctx)
}
