// Code generated by MockGen. DO NOT EDIT.
// Source: conversationGroup.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=conversationGroup.go -destination=mock/conversationGroup.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationGroupRepository is a mock of ConversationGroupRepository interface.
type MockConversationGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationGroupRepositoryMockRecorder is the mock recorder for MockConversationGroupRepository.
type MockConversationGroupRepositoryMockRecorder struct {
	mock *MockConversationGroupRepository
}

// NewMockConversationGroupRepository creates a new mock instance.
func NewMockConversationGroupRepository(ctrl *gomock.Controller) *MockConversationGroupRepository {
	mock := &MockConversationGroupRepository{ctrl: ctrl}
	mock.recorder = &MockConversationGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationGroupRepository) EXPECT() *MockConversationGroupRepositoryMockRecorder {
	return m.recorder
}

// CreateConversationGroup mocks base method.
func (m *MockConversationGroupRepository) CreateConversationGroup(ctx context.Context) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversationGroup", ctx)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversationGroup indicates an expected call of CreateConversationGroup.
func (mr *MockConversationGroupRepositoryMockRecorder) CreateConversationGroup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversationGroup", reflect.TypeOf((*MockConversationGroupRepository)(nil).CreateConversationGroup), ctx)
}

// DeleteConversationGroup mocks base method.
func (m *MockConversationGroupRepository) DeleteConversationGroup(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversationGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversationGroup indicates an expected call of DeleteConversationGroup.
func (mr *MockConversationGroupRepositoryMockRecorder) DeleteConversationGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversationGroup", reflect.TypeOf((*MockConversationGroupRepository)(nil).DeleteConversationGroup), ctx, id)
}

// GetConversationGroupByID mocks base method.
func (m *MockConversationGroupRepository) GetConversationGroupByID(ctx context.Context, id int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationGroupByID", ctx, id)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationGroupByID indicates an expected call of GetConversationGroupByID.
func (mr *MockConversationGroupRepositoryMockRecorder) GetConversationGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationGroupByID", reflect.TypeOf((*MockConversationGroupRepository)(nil).GetConversationGroupByID), ctx, id)
}

// ListConversationGroups mocks base method.
func (m *MockConversationGroupRepository) ListConversationGroups(ctx context.Context) ([]*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversationGroups", ctx)
	ret0, _ := ret[0].([]*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversationGroups indicates an expected call of ListConversationGroups.
func (mr *MockConversationGroupRepositoryMockRecorder) ListConversationGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversationGroups", reflect.TypeOf((*MockConversationGroupRepository)(nil).ListConversationGroups), ctx)
}
