// Code generated by MockGen. DO NOT EDIT.
// Source: discordGuild.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordGuild.go -destination=mock/discordGuild.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordGuildRepository is a mock of DiscordGuildRepository interface.
type MockDiscordGuildRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordGuildRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordGuildRepositoryMockRecorder is the mock recorder for MockDiscordGuildRepository.
type MockDiscordGuildRepositoryMockRecorder struct {
	mock *MockDiscordGuildRepository
}

// NewMockDiscordGuildRepository creates a new mock instance.
func NewMockDiscordGuildRepository(ctrl *gomock.Controller) *MockDiscordGuildRepository {
	mock := &MockDiscordGuildRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordGuildRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordGuildRepository) EXPECT() *MockDiscordGuildRepositoryMockRecorder {
	return m.recorder
}

// CreateDiscordGuild mocks base method.
func (m *MockDiscordGuildRepository) CreateDiscordGuild(ctx context.Context, params domain.DiscordGuild) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordGuild", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordGuild indicates an expected call of CreateDiscordGuild.
func (mr *MockDiscordGuildRepositoryMockRecorder) CreateDiscordGuild(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordGuild", reflect.TypeOf((*MockDiscordGuildRepository)(nil).CreateDiscordGuild), ctx, params)
}

// DeleteDiscordGuild mocks base method.
func (m *MockDiscordGuildRepository) DeleteDiscordGuild(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordGuild", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordGuild indicates an expected call of DeleteDiscordGuild.
func (mr *MockDiscordGuildRepositoryMockRecorder) DeleteDiscordGuild(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordGuild", reflect.TypeOf((*MockDiscordGuildRepository)(nil).DeleteDiscordGuild), ctx, id)
}

// GetDiscordGuildByChannelID mocks base method.
func (m *MockDiscordGuildRepository) GetDiscordGuildByChannelID(ctx context.Context, channelID string) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordGuildByChannelID", ctx, channelID)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordGuildByChannelID indicates an expected call of GetDiscordGuildByChannelID.
func (mr *MockDiscordGuildRepositoryMockRecorder) GetDiscordGuildByChannelID(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordGuildByChannelID", reflect.TypeOf((*MockDiscordGuildRepository)(nil).GetDiscordGuildByChannelID), ctx, channelID)
}

// GetDiscordGuildByID mocks base method.
func (m *MockDiscordGuildRepository) GetDiscordGuildByID(ctx context.Context, id string) (*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordGuildByID", ctx, id)
	ret0, _ := ret[0].(*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordGuildByID indicates an expected call of GetDiscordGuildByID.
func (mr *MockDiscordGuildRepositoryMockRecorder) GetDiscordGuildByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordGuildByID", reflect.TypeOf((*MockDiscordGuildRepository)(nil).GetDiscordGuildByID), ctx, id)
}

// ListDiscordGuilds mocks base method.
func (m *MockDiscordGuildRepository) ListDiscordGuilds(ctx context.Context) ([]*domain.DiscordGuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordGuilds", ctx)
	ret0, _ := ret[0].([]*domain.DiscordGuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordGuilds indicates an expected call of ListDiscordGuilds.
func (mr *MockDiscordGuildRepositoryMockRecorder) ListDiscordGuilds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordGuilds", reflect.TypeOf((*MockDiscordGuildRepository)(nil).ListDiscordGuilds), ctx)
}
