// Code generated by MockGen. DO NOT EDIT.
// Source: discordUser.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordUser.go -destination=mock/discordUser.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordUserRepository is a mock of DiscordUserRepository interface.
type MockDiscordUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordUserRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordUserRepositoryMockRecorder is the mock recorder for MockDiscordUserRepository.
type MockDiscordUserRepositoryMockRecorder struct {
	mock *MockDiscordUserRepository
}

// NewMockDiscordUserRepository creates a new mock instance.
func NewMockDiscordUserRepository(ctrl *gomock.Controller) *MockDiscordUserRepository {
	mock := &MockDiscordUserRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordUserRepository) EXPECT() *MockDiscordUserRepositoryMockRecorder {
	return m.recorder
}

// CreateDiscordUser mocks base method.
func (m *MockDiscordUserRepository) CreateDiscordUser(ctx context.Context, params domain.DiscordUser) (*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordUser", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordUser indicates an expected call of CreateDiscordUser.
func (mr *MockDiscordUserRepositoryMockRecorder) CreateDiscordUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordUser", reflect.TypeOf((*MockDiscordUserRepository)(nil).CreateDiscordUser), ctx, params)
}

// DeleteDiscordUser mocks base method.
func (m *MockDiscordUserRepository) DeleteDiscordUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordUser indicates an expected call of DeleteDiscordUser.
func (mr *MockDiscordUserRepositoryMockRecorder) DeleteDiscordUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordUser", reflect.TypeOf((*MockDiscordUserRepository)(nil).DeleteDiscordUser), ctx, id)
}

// GetDiscordUserByID mocks base method.
func (m *MockDiscordUserRepository) GetDiscordUserByID(ctx context.Context, id string) (*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordUserByID indicates an expected call of GetDiscordUserByID.
func (mr *MockDiscordUserRepositoryMockRecorder) GetDiscordUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordUserByID", reflect.TypeOf((*MockDiscordUserRepository)(nil).GetDiscordUserByID), ctx, id)
}

// ListDiscordUsers mocks base method.
func (m *MockDiscordUserRepository) ListDiscordUsers(ctx context.Context) ([]*domain.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordUsers", ctx)
	ret0, _ := ret[0].([]*domain.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordUsers indicates an expected call of ListDiscordUsers.
func (mr *MockDiscordUserRepositoryMockRecorder) ListDiscordUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordUsers", reflect.TypeOf((*MockDiscordUserRepository)(nil).ListDiscordUsers), ctx)
}
