// Code generated by MockGen. DO NOT EDIT.
// Source: discordChannel.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordChannel.go -destination=mock/discordChannel.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordChannelRepository is a mock of DiscordChannelRepository interface.
type MockDiscordChannelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordChannelRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordChannelRepositoryMockRecorder is the mock recorder for MockDiscordChannelRepository.
type MockDiscordChannelRepositoryMockRecorder struct {
	mock *MockDiscordChannelRepository
}

// NewMockDiscordChannelRepository creates a new mock instance.
func NewMockDiscordChannelRepository(ctrl *gomock.Controller) *MockDiscordChannelRepository {
	mock := &MockDiscordChannelRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordChannelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordChannelRepository) EXPECT() *MockDiscordChannelRepositoryMockRecorder {
	return m.recorder
}

// CreateDiscordChannel mocks base method.
func (m *MockDiscordChannelRepository) CreateDiscordChannel(ctx context.Context, params domain.DiscordChannel) (*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordChannel", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordChannel indicates an expected call of CreateDiscordChannel.
func (mr *MockDiscordChannelRepositoryMockRecorder) CreateDiscordChannel(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordChannel", reflect.TypeOf((*MockDiscordChannelRepository)(nil).CreateDiscordChannel), ctx, params)
}

// DeleteDiscordChannel mocks base method.
func (m *MockDiscordChannelRepository) DeleteDiscordChannel(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordChannel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordChannel indicates an expected call of DeleteDiscordChannel.
func (mr *MockDiscordChannelRepositoryMockRecorder) DeleteDiscordChannel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordChannel", reflect.TypeOf((*MockDiscordChannelRepository)(nil).DeleteDiscordChannel), ctx, id)
}

// GetDiscordChannelByID mocks base method.
func (m *MockDiscordChannelRepository) GetDiscordChannelByID(ctx context.Context, id string) (*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordChannelByID", ctx, id)
	ret0, _ := ret[0].(*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordChannelByID indicates an expected call of GetDiscordChannelByID.
func (mr *MockDiscordChannelRepositoryMockRecorder) GetDiscordChannelByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordChannelByID", reflect.TypeOf((*MockDiscordChannelRepository)(nil).GetDiscordChannelByID), ctx, id)
}

// ListDiscordChannels mocks base method.
func (m *MockDiscordChannelRepository) ListDiscordChannels(ctx context.Context) ([]*domain.DiscordChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordChannels", ctx)
	ret0, _ := ret[0].([]*domain.DiscordChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordChannels indicates an expected call of ListDiscordChannels.
func (mr *MockDiscordChannelRepositoryMockRecorder) ListDiscordChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordChannels", reflect.TypeOf((*MockDiscordChannelRepository)(nil).ListDiscordChannels), ctx)
}
