// Code generated by MockGen. DO NOT EDIT.
// Source: discordMessage.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discordMessage.go -destination=mock/discordMessage.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordMessageRepository is a mock of DiscordMessageRepository interface.
type MockDiscordMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordMessageRepositoryMockRecorder is the mock recorder for MockDiscordMessageRepository.
type MockDiscordMessageRepositoryMockRecorder struct {
	mock *MockDiscordMessageRepository
}

// NewMockDiscordMessageRepository creates a new mock instance.
func NewMockDiscordMessageRepository(ctrl *gomock.Controller) *MockDiscordMessageRepository {
	mock := &MockDiscordMessageRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordMessageRepository) EXPECT() *MockDiscordMessageRepositoryMockRecorder {
	return m.recorder
}

// CreateDiscordMessage mocks base method.
func (m *MockDiscordMessageRepository) CreateDiscordMessage(ctx context.Context, params domain.DiscordMessage) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscordMessage", ctx, params)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscordMessage indicates an expected call of CreateDiscordMessage.
func (mr *MockDiscordMessageRepositoryMockRecorder) CreateDiscordMessage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscordMessage", reflect.TypeOf((*MockDiscordMessageRepository)(nil).CreateDiscordMessage), ctx, params)
}

// DeleteDiscordMessage mocks base method.
func (m *MockDiscordMessageRepository) DeleteDiscordMessage(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscordMessage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscordMessage indicates an expected call of DeleteDiscordMessage.
func (mr *MockDiscordMessageRepositoryMockRecorder) DeleteDiscordMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscordMessage", reflect.TypeOf((*MockDiscordMessageRepository)(nil).DeleteDiscordMessage), ctx, id)
}

// GetDiscordMessageByID mocks base method.
func (m *MockDiscordMessageRepository) GetDiscordMessageByID(ctx context.Context, id string) (*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordMessageByID", ctx, id)
	ret0, _ := ret[0].(*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordMessageByID indicates an expected call of GetDiscordMessageByID.
func (mr *MockDiscordMessageRepositoryMockRecorder) GetDiscordMessageByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordMessageByID", reflect.TypeOf((*MockDiscordMessageRepository)(nil).GetDiscordMessageByID), ctx, id)
}

// ListDiscordMessages mocks base method.
func (m *MockDiscordMessageRepository) ListDiscordMessages(ctx context.Context) ([]*domain.DiscordMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscordMessages", ctx)
	ret0, _ := ret[0].([]*domain.DiscordMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscordMessages indicates an expected call of ListDiscordMessages.
func (mr *MockDiscordMessageRepositoryMockRecorder) ListDiscordMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscordMessages", reflect.TypeOf((*MockDiscordMessageRepository)(nil).ListDiscordMessages), ctx)
}
