// Code generated by MockGen. DO NOT EDIT.
// Source: systemPrompt.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=systemPrompt.go -destination=mock/systemPrompt.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemPromptRepository is a mock of SystemPromptRepository interface.
type MockSystemPromptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemPromptRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemPromptRepositoryMockRecorder is the mock recorder for MockSystemPromptRepository.
type MockSystemPromptRepositoryMockRecorder struct {
	mock *MockSystemPromptRepository
}

// NewMockSystemPromptRepository creates a new mock instance.
func NewMockSystemPromptRepository(ctrl *gomock.Controller) *MockSystemPromptRepository {
	mock := &MockSystemPromptRepository{ctrl: ctrl}
	mock.recorder = &MockSystemPromptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemPromptRepository) EXPECT() *MockSystemPromptRepositoryMockRecorder {
	return m.recorder
}

// GetSystemPromptByID mocks base method.
func (m *MockSystemPromptRepository) GetSystemPromptByID(ctx context.Context, id int) (*domain.SystemPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPromptByID", ctx, id)
	ret0, _ := ret[0].(*domain.SystemPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPromptByID indicates an expected call of GetSystemPromptByID.
func (mr *MockSystemPromptRepositoryMockRecorder) GetSystemPromptByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPromptByID", reflect.TypeOf((*MockSystemPromptRepository)(nil).GetSystemPromptByID), ctx, id)
}
