// Code generated by MockGen. DO NOT EDIT.
// Source: discord.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=discord.go -destination=mock/discord.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/kizuna-org/akari/pkg/discord/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordRepository is a mock of DiscordRepository interface.
type MockDiscordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordRepositoryMockRecorder is the mock recorder for MockDiscordRepository.
type MockDiscordRepositoryMockRecorder struct {
	mock *MockDiscordRepository
}

// NewMockDiscordRepository creates a new mock instance.
func NewMockDiscordRepository(ctrl *gomock.Controller) *MockDiscordRepository {
	mock := &MockDiscordRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordRepository) EXPECT() *MockDiscordRepositoryMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockDiscordRepository) GetMessage(ctx context.Context, channelID, messageID string) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, channelID, messageID)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockDiscordRepositoryMockRecorder) GetMessage(ctx, channelID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockDiscordRepository)(nil).GetMessage), ctx, channelID, messageID)
}

// SendMessage mocks base method.
func (m *MockDiscordRepository) SendMessage(ctx context.Context, channelID, content string) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordRepositoryMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordRepository)(nil).SendMessage), ctx, channelID, content)
}

// Start mocks base method.
func (m *MockDiscordRepository) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockDiscordRepositoryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDiscordRepository)(nil).Start))
}

// Stop mocks base method.
func (m *MockDiscordRepository) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDiscordRepositoryMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDiscordRepository)(nil).Stop))
}
