// Code generated by MockGen. DO NOT EDIT.
// Source: llm.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=llm.go -destination=mock/llm.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/pkg/llm/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGeminiRepository is a mock of GeminiRepository interface.
type MockGeminiRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiRepositoryMockRecorder
	isgomock struct{}
}

// MockGeminiRepositoryMockRecorder is the mock recorder for MockGeminiRepository.
type MockGeminiRepositoryMockRecorder struct {
	mock *MockGeminiRepository
}

// NewMockGeminiRepository creates a new mock instance.
func NewMockGeminiRepository(ctrl *gomock.Controller) *MockGeminiRepository {
	mock := &MockGeminiRepository{ctrl: ctrl}
	mock.recorder = &MockGeminiRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiRepository) EXPECT() *MockGeminiRepositoryMockRecorder {
	return m.recorder
}

// SendChatMessage mocks base method.
func (m *MockGeminiRepository) SendChatMessage(ctx context.Context, systemPrompt string, history []*domain.Content, message string, functions []domain.Function) ([]*string, []*domain.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChatMessage", ctx, systemPrompt, history, message, functions)
	ret0, _ := ret[0].([]*string)
	ret1, _ := ret[1].([]*domain.Part)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendChatMessage indicates an expected call of SendChatMessage.
func (mr *MockGeminiRepositoryMockRecorder) SendChatMessage(ctx, systemPrompt, history, message, functions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChatMessage", reflect.TypeOf((*MockGeminiRepository)(nil).SendChatMessage), ctx, systemPrompt, history, message, functions)
}
