// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=client.go -destination=mock/client.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	ent "github.com/kizuna-org/akari/gen/ent"
	domain "github.com/kizuna-org/akari/pkg/database/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CharacterClient mocks base method.
func (m *MockClient) CharacterClient() *ent.CharacterClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CharacterClient")
	ret0, _ := ret[0].(*ent.CharacterClient)
	return ret0
}

// CharacterClient indicates an expected call of CharacterClient.
func (mr *MockClientMockRecorder) CharacterClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CharacterClient", reflect.TypeOf((*MockClient)(nil).CharacterClient))
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// DiscordChannelClient mocks base method.
func (m *MockClient) DiscordChannelClient() *ent.DiscordChannelClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscordChannelClient")
	ret0, _ := ret[0].(*ent.DiscordChannelClient)
	return ret0
}

// DiscordChannelClient indicates an expected call of DiscordChannelClient.
func (mr *MockClientMockRecorder) DiscordChannelClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscordChannelClient", reflect.TypeOf((*MockClient)(nil).DiscordChannelClient))
}

// DiscordGuildClient mocks base method.
func (m *MockClient) DiscordGuildClient() *ent.DiscordGuildClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscordGuildClient")
	ret0, _ := ret[0].(*ent.DiscordGuildClient)
	return ret0
}

// DiscordGuildClient indicates an expected call of DiscordGuildClient.
func (mr *MockClientMockRecorder) DiscordGuildClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscordGuildClient", reflect.TypeOf((*MockClient)(nil).DiscordGuildClient))
}

// DiscordMessageClient mocks base method.
func (m *MockClient) DiscordMessageClient() *ent.DiscordMessageClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscordMessageClient")
	ret0, _ := ret[0].(*ent.DiscordMessageClient)
	return ret0
}

// DiscordMessageClient indicates an expected call of DiscordMessageClient.
func (mr *MockClientMockRecorder) DiscordMessageClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscordMessageClient", reflect.TypeOf((*MockClient)(nil).DiscordMessageClient))
}

// Ping mocks base method.
func (m *MockClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockClient)(nil).Ping), ctx)
}

// SystemPromptClient mocks base method.
func (m *MockClient) SystemPromptClient() *ent.SystemPromptClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemPromptClient")
	ret0, _ := ret[0].(*ent.SystemPromptClient)
	return ret0
}

// SystemPromptClient indicates an expected call of SystemPromptClient.
func (mr *MockClientMockRecorder) SystemPromptClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemPromptClient", reflect.TypeOf((*MockClient)(nil).SystemPromptClient))
}

// WithTx mocks base method.
func (m *MockClient) WithTx(ctx context.Context, txFunc domain.TxFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, txFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockClientMockRecorder) WithTx(ctx, txFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockClient)(nil).WithTx), ctx, txFunc)
}
