// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=repository.go -destination=mock/repository.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/internal/message/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// SaveMessage mocks base method.
func (m *MockMessageRepository) SaveMessage(ctx context.Context, message *domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageRepositoryMockRecorder) SaveMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageRepository)(nil).SaveMessage), ctx, message)
}

// MockResponseRepository is a mock of ResponseRepository interface.
type MockResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResponseRepositoryMockRecorder
	isgomock struct{}
}

// MockResponseRepositoryMockRecorder is the mock recorder for MockResponseRepository.
type MockResponseRepositoryMockRecorder struct {
	mock *MockResponseRepository
}

// NewMockResponseRepository creates a new mock instance.
func NewMockResponseRepository(ctrl *gomock.Controller) *MockResponseRepository {
	mock := &MockResponseRepository{ctrl: ctrl}
	mock.recorder = &MockResponseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseRepository) EXPECT() *MockResponseRepositoryMockRecorder {
	return m.recorder
}

// SaveResponse mocks base method.
func (m *MockResponseRepository) SaveResponse(ctx context.Context, response *domain.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResponse", ctx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResponse indicates an expected call of SaveResponse.
func (mr *MockResponseRepositoryMockRecorder) SaveResponse(ctx, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResponse", reflect.TypeOf((*MockResponseRepository)(nil).SaveResponse), ctx, response)
}

// MockLLMRepository is a mock of LLMRepository interface.
type MockLLMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMRepositoryMockRecorder
	isgomock struct{}
}

// MockLLMRepositoryMockRecorder is the mock recorder for MockLLMRepository.
type MockLLMRepositoryMockRecorder struct {
	mock *MockLLMRepository
}

// NewMockLLMRepository creates a new mock instance.
func NewMockLLMRepository(ctrl *gomock.Controller) *MockLLMRepository {
	mock := &MockLLMRepository{ctrl: ctrl}
	mock.recorder = &MockLLMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMRepository) EXPECT() *MockLLMRepositoryMockRecorder {
	return m.recorder
}

// GenerateResponse mocks base method.
func (m *MockLLMRepository) GenerateResponse(ctx context.Context, systemPrompt, userMessage string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateResponse", ctx, systemPrompt, userMessage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateResponse indicates an expected call of GenerateResponse.
func (mr *MockLLMRepositoryMockRecorder) GenerateResponse(ctx, systemPrompt, userMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateResponse", reflect.TypeOf((*MockLLMRepository)(nil).GenerateResponse), ctx, systemPrompt, userMessage)
}

// MockDiscordRepository is a mock of DiscordRepository interface.
type MockDiscordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordRepositoryMockRecorder is the mock recorder for MockDiscordRepository.
type MockDiscordRepositoryMockRecorder struct {
	mock *MockDiscordRepository
}

// NewMockDiscordRepository creates a new mock instance.
func NewMockDiscordRepository(ctrl *gomock.Controller) *MockDiscordRepository {
	mock := &MockDiscordRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordRepository) EXPECT() *MockDiscordRepositoryMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockDiscordRepository) SendMessage(ctx context.Context, channelID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordRepositoryMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordRepository)(nil).SendMessage), ctx, channelID, content)
}

// MockValidationRepository is a mock of ValidationRepository interface.
type MockValidationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRepositoryMockRecorder
	isgomock struct{}
}

// MockValidationRepositoryMockRecorder is the mock recorder for MockValidationRepository.
type MockValidationRepositoryMockRecorder struct {
	mock *MockValidationRepository
}

// NewMockValidationRepository creates a new mock instance.
func NewMockValidationRepository(ctrl *gomock.Controller) *MockValidationRepository {
	mock := &MockValidationRepository{ctrl: ctrl}
	mock.recorder = &MockValidationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRepository) EXPECT() *MockValidationRepositoryMockRecorder {
	return m.recorder
}

// ContainsBotName mocks base method.
func (m *MockValidationRepository) ContainsBotName(message *domain.Message, botNamePattern string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsBotName", message, botNamePattern)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsBotName indicates an expected call of ContainsBotName.
func (mr *MockValidationRepositoryMockRecorder) ContainsBotName(message, botNamePattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsBotName", reflect.TypeOf((*MockValidationRepository)(nil).ContainsBotName), message, botNamePattern)
}

// IsBotMentioned mocks base method.
func (m *MockValidationRepository) IsBotMentioned(message *domain.Message, botUserID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBotMentioned", message, botUserID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBotMentioned indicates an expected call of IsBotMentioned.
func (mr *MockValidationRepositoryMockRecorder) IsBotMentioned(message, botUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBotMentioned", reflect.TypeOf((*MockValidationRepository)(nil).IsBotMentioned), message, botUserID)
}

// ShouldProcessMessage mocks base method.
func (m *MockValidationRepository) ShouldProcessMessage(message *domain.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessMessage", message)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessMessage indicates an expected call of ShouldProcessMessage.
func (mr *MockValidationRepositoryMockRecorder) ShouldProcessMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessMessage", reflect.TypeOf((*MockValidationRepository)(nil).ShouldProcessMessage), message)
}

// MockCharacterRepository is a mock of CharacterRepository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// GetCharacterByID mocks base method.
func (m *MockCharacterRepository) GetCharacterByID(ctx context.Context, characterID int) (*domain.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByID", ctx, characterID)
	ret0, _ := ret[0].(*domain.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByID indicates an expected call of GetCharacterByID.
func (mr *MockCharacterRepositoryMockRecorder) GetCharacterByID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByID", reflect.TypeOf((*MockCharacterRepository)(nil).GetCharacterByID), ctx, characterID)
}

// MockSystemPromptRepository is a mock of SystemPromptRepository interface.
type MockSystemPromptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemPromptRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemPromptRepositoryMockRecorder is the mock recorder for MockSystemPromptRepository.
type MockSystemPromptRepositoryMockRecorder struct {
	mock *MockSystemPromptRepository
}

// NewMockSystemPromptRepository creates a new mock instance.
func NewMockSystemPromptRepository(ctrl *gomock.Controller) *MockSystemPromptRepository {
	mock := &MockSystemPromptRepository{ctrl: ctrl}
	mock.recorder = &MockSystemPromptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemPromptRepository) EXPECT() *MockSystemPromptRepositoryMockRecorder {
	return m.recorder
}

// GetSystemPromptByID mocks base method.
func (m *MockSystemPromptRepository) GetSystemPromptByID(ctx context.Context, id int) (*domain.SystemPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPromptByID", ctx, id)
	ret0, _ := ret[0].(*domain.SystemPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPromptByID indicates an expected call of GetSystemPromptByID.
func (mr *MockSystemPromptRepositoryMockRecorder) GetSystemPromptByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPromptByID", reflect.TypeOf((*MockSystemPromptRepository)(nil).GetSystemPromptByID), ctx, id)
}

// MockConversationRepository is a mock of ConversationRepository interface.
type MockConversationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationRepositoryMockRecorder is the mock recorder for MockConversationRepository.
type MockConversationRepositoryMockRecorder struct {
	mock *MockConversationRepository
}

// NewMockConversationRepository creates a new mock instance.
func NewMockConversationRepository(ctrl *gomock.Controller) *MockConversationRepository {
	mock := &MockConversationRepository{ctrl: ctrl}
	mock.recorder = &MockConversationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepository) EXPECT() *MockConversationRepositoryMockRecorder {
	return m.recorder
}

// CreateConversation mocks base method.
func (m *MockConversationRepository) CreateConversation(ctx context.Context, messageID string, userID int, conversationGroupID *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, messageID, userID, conversationGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockConversationRepositoryMockRecorder) CreateConversation(ctx, messageID, userID, conversationGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockConversationRepository)(nil).CreateConversation), ctx, messageID, userID, conversationGroupID)
}

// MockConversationGroupRepository is a mock of ConversationGroupRepository interface.
type MockConversationGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationGroupRepositoryMockRecorder is the mock recorder for MockConversationGroupRepository.
type MockConversationGroupRepositoryMockRecorder struct {
	mock *MockConversationGroupRepository
}

// NewMockConversationGroupRepository creates a new mock instance.
func NewMockConversationGroupRepository(ctrl *gomock.Controller) *MockConversationGroupRepository {
	mock := &MockConversationGroupRepository{ctrl: ctrl}
	mock.recorder = &MockConversationGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationGroupRepository) EXPECT() *MockConversationGroupRepositoryMockRecorder {
	return m.recorder
}

// CreateConversationGroup mocks base method.
func (m *MockConversationGroupRepository) CreateConversationGroup(ctx context.Context, characterID int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversationGroup", ctx, characterID)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversationGroup indicates an expected call of CreateConversationGroup.
func (mr *MockConversationGroupRepositoryMockRecorder) CreateConversationGroup(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversationGroup", reflect.TypeOf((*MockConversationGroupRepository)(nil).CreateConversationGroup), ctx, characterID)
}

// GetConversationGroupByCharacterID mocks base method.
func (m *MockConversationGroupRepository) GetConversationGroupByCharacterID(ctx context.Context, characterID int) (*domain.ConversationGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationGroupByCharacterID", ctx, characterID)
	ret0, _ := ret[0].(*domain.ConversationGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationGroupByCharacterID indicates an expected call of GetConversationGroupByCharacterID.
func (mr *MockConversationGroupRepositoryMockRecorder) GetConversationGroupByCharacterID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationGroupByCharacterID", reflect.TypeOf((*MockConversationGroupRepository)(nil).GetConversationGroupByCharacterID), ctx, characterID)
}

// MockDiscordUserRepository is a mock of DiscordUserRepository interface.
type MockDiscordUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordUserRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordUserRepositoryMockRecorder is the mock recorder for MockDiscordUserRepository.
type MockDiscordUserRepositoryMockRecorder struct {
	mock *MockDiscordUserRepository
}

// NewMockDiscordUserRepository creates a new mock instance.
func NewMockDiscordUserRepository(ctrl *gomock.Controller) *MockDiscordUserRepository {
	mock := &MockDiscordUserRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordUserRepository) EXPECT() *MockDiscordUserRepositoryMockRecorder {
	return m.recorder
}

// GetDiscordUserByID mocks base method.
func (m *MockDiscordUserRepository) GetDiscordUserByID(ctx context.Context, discordUserID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordUserByID", ctx, discordUserID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordUserByID indicates an expected call of GetDiscordUserByID.
func (mr *MockDiscordUserRepositoryMockRecorder) GetDiscordUserByID(ctx, discordUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordUserByID", reflect.TypeOf((*MockDiscordUserRepository)(nil).GetDiscordUserByID), ctx, discordUserID)
}

// GetOrCreateDiscordUser mocks base method.
func (m *MockDiscordUserRepository) GetOrCreateDiscordUser(ctx context.Context, discordUserID, username string, isBot bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateDiscordUser", ctx, discordUserID, username, isBot)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateDiscordUser indicates an expected call of GetOrCreateDiscordUser.
func (mr *MockDiscordUserRepositoryMockRecorder) GetOrCreateDiscordUser(ctx, discordUserID, username, isBot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateDiscordUser", reflect.TypeOf((*MockDiscordUserRepository)(nil).GetOrCreateDiscordUser), ctx, discordUserID, username, isBot)
}

// MockAkariUserRepository is a mock of AkariUserRepository interface.
type MockAkariUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAkariUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAkariUserRepositoryMockRecorder is the mock recorder for MockAkariUserRepository.
type MockAkariUserRepositoryMockRecorder struct {
	mock *MockAkariUserRepository
}

// NewMockAkariUserRepository creates a new mock instance.
func NewMockAkariUserRepository(ctrl *gomock.Controller) *MockAkariUserRepository {
	mock := &MockAkariUserRepository{ctrl: ctrl}
	mock.recorder = &MockAkariUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAkariUserRepository) EXPECT() *MockAkariUserRepositoryMockRecorder {
	return m.recorder
}

// GetOrCreateAkariUserByDiscordUserID mocks base method.
func (m *MockAkariUserRepository) GetOrCreateAkariUserByDiscordUserID(ctx context.Context, discordUserID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateAkariUserByDiscordUserID", ctx, discordUserID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateAkariUserByDiscordUserID indicates an expected call of GetOrCreateAkariUserByDiscordUserID.
func (mr *MockAkariUserRepositoryMockRecorder) GetOrCreateAkariUserByDiscordUserID(ctx, discordUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateAkariUserByDiscordUserID", reflect.TypeOf((*MockAkariUserRepository)(nil).GetOrCreateAkariUserByDiscordUserID), ctx, discordUserID)
}
