// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=repository.go -destination=mock/repository.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kizuna-org/akari/internal/message/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// SaveMessage mocks base method.
func (m *MockMessageRepository) SaveMessage(ctx context.Context, message *domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageRepositoryMockRecorder) SaveMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageRepository)(nil).SaveMessage), ctx, message)
}

// MockResponseRepository is a mock of ResponseRepository interface.
type MockResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResponseRepositoryMockRecorder
	isgomock struct{}
}

// MockResponseRepositoryMockRecorder is the mock recorder for MockResponseRepository.
type MockResponseRepositoryMockRecorder struct {
	mock *MockResponseRepository
}

// NewMockResponseRepository creates a new mock instance.
func NewMockResponseRepository(ctrl *gomock.Controller) *MockResponseRepository {
	mock := &MockResponseRepository{ctrl: ctrl}
	mock.recorder = &MockResponseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseRepository) EXPECT() *MockResponseRepositoryMockRecorder {
	return m.recorder
}

// SaveResponse mocks base method.
func (m *MockResponseRepository) SaveResponse(ctx context.Context, response *domain.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResponse", ctx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResponse indicates an expected call of SaveResponse.
func (mr *MockResponseRepositoryMockRecorder) SaveResponse(ctx, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResponse", reflect.TypeOf((*MockResponseRepository)(nil).SaveResponse), ctx, response)
}

// MockLLMRepository is a mock of LLMRepository interface.
type MockLLMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMRepositoryMockRecorder
	isgomock struct{}
}

// MockLLMRepositoryMockRecorder is the mock recorder for MockLLMRepository.
type MockLLMRepositoryMockRecorder struct {
	mock *MockLLMRepository
}

// NewMockLLMRepository creates a new mock instance.
func NewMockLLMRepository(ctrl *gomock.Controller) *MockLLMRepository {
	mock := &MockLLMRepository{ctrl: ctrl}
	mock.recorder = &MockLLMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMRepository) EXPECT() *MockLLMRepositoryMockRecorder {
	return m.recorder
}

// GenerateResponse mocks base method.
func (m *MockLLMRepository) GenerateResponse(ctx context.Context, systemPrompt, userMessage string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateResponse", ctx, systemPrompt, userMessage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateResponse indicates an expected call of GenerateResponse.
func (mr *MockLLMRepositoryMockRecorder) GenerateResponse(ctx, systemPrompt, userMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateResponse", reflect.TypeOf((*MockLLMRepository)(nil).GenerateResponse), ctx, systemPrompt, userMessage)
}

// MockDiscordRepository is a mock of DiscordRepository interface.
type MockDiscordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordRepositoryMockRecorder is the mock recorder for MockDiscordRepository.
type MockDiscordRepositoryMockRecorder struct {
	mock *MockDiscordRepository
}

// NewMockDiscordRepository creates a new mock instance.
func NewMockDiscordRepository(ctrl *gomock.Controller) *MockDiscordRepository {
	mock := &MockDiscordRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordRepository) EXPECT() *MockDiscordRepositoryMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockDiscordRepository) SendMessage(ctx context.Context, channelID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordRepositoryMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordRepository)(nil).SendMessage), ctx, channelID, content)
}

// MockValidationRepository is a mock of ValidationRepository interface.
type MockValidationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRepositoryMockRecorder
	isgomock struct{}
}

// MockValidationRepositoryMockRecorder is the mock recorder for MockValidationRepository.
type MockValidationRepositoryMockRecorder struct {
	mock *MockValidationRepository
}

// NewMockValidationRepository creates a new mock instance.
func NewMockValidationRepository(ctrl *gomock.Controller) *MockValidationRepository {
	mock := &MockValidationRepository{ctrl: ctrl}
	mock.recorder = &MockValidationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRepository) EXPECT() *MockValidationRepositoryMockRecorder {
	return m.recorder
}

// ContainsBotName mocks base method.
func (m *MockValidationRepository) ContainsBotName(message *domain.Message, botNamePattern string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsBotName", message, botNamePattern)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsBotName indicates an expected call of ContainsBotName.
func (mr *MockValidationRepositoryMockRecorder) ContainsBotName(message, botNamePattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsBotName", reflect.TypeOf((*MockValidationRepository)(nil).ContainsBotName), message, botNamePattern)
}

// IsBotMentioned mocks base method.
func (m *MockValidationRepository) IsBotMentioned(message *domain.Message, botUserID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBotMentioned", message, botUserID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBotMentioned indicates an expected call of IsBotMentioned.
func (mr *MockValidationRepositoryMockRecorder) IsBotMentioned(message, botUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBotMentioned", reflect.TypeOf((*MockValidationRepository)(nil).IsBotMentioned), message, botUserID)
}

// ShouldProcessMessage mocks base method.
func (m *MockValidationRepository) ShouldProcessMessage(message *domain.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessMessage", message)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessMessage indicates an expected call of ShouldProcessMessage.
func (mr *MockValidationRepositoryMockRecorder) ShouldProcessMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessMessage", reflect.TypeOf((*MockValidationRepository)(nil).ShouldProcessMessage), message)
}

// MockCharacterRepository is a mock of CharacterRepository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// GetCharacterByID mocks base method.
func (m *MockCharacterRepository) GetCharacterByID(ctx context.Context, characterID int) (*domain.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByID", ctx, characterID)
	ret0, _ := ret[0].(*domain.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByID indicates an expected call of GetCharacterByID.
func (mr *MockCharacterRepositoryMockRecorder) GetCharacterByID(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByID", reflect.TypeOf((*MockCharacterRepository)(nil).GetCharacterByID), ctx, characterID)
}

// MockSystemPromptRepository is a mock of SystemPromptRepository interface.
type MockSystemPromptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemPromptRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemPromptRepositoryMockRecorder is the mock recorder for MockSystemPromptRepository.
type MockSystemPromptRepositoryMockRecorder struct {
	mock *MockSystemPromptRepository
}

// NewMockSystemPromptRepository creates a new mock instance.
func NewMockSystemPromptRepository(ctrl *gomock.Controller) *MockSystemPromptRepository {
	mock := &MockSystemPromptRepository{ctrl: ctrl}
	mock.recorder = &MockSystemPromptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemPromptRepository) EXPECT() *MockSystemPromptRepositoryMockRecorder {
	return m.recorder
}

// GetSystemPromptByID mocks base method.
func (m *MockSystemPromptRepository) GetSystemPromptByID(ctx context.Context, id int) (*domain.SystemPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPromptByID", ctx, id)
	ret0, _ := ret[0].(*domain.SystemPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPromptByID indicates an expected call of GetSystemPromptByID.
func (mr *MockSystemPromptRepositoryMockRecorder) GetSystemPromptByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPromptByID", reflect.TypeOf((*MockSystemPromptRepository)(nil).GetSystemPromptByID), ctx, id)
}
