// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=repository.go -destination=mock/repository.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	regexp "regexp"

	domain "github.com/kizuna-org/akari/internal/message/domain"
	entity "github.com/kizuna-org/akari/internal/message/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterRepository is a mock of CharacterRepository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCharacterRepository) Get(ctx context.Context, characterID int) (*domain.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, characterID)
	ret0, _ := ret[0].(*domain.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCharacterRepositoryMockRecorder) Get(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCharacterRepository)(nil).Get), ctx, characterID)
}

// MockDiscordRepository is a mock of DiscordRepository interface.
type MockDiscordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordRepositoryMockRecorder is the mock recorder for MockDiscordRepository.
type MockDiscordRepositoryMockRecorder struct {
	mock *MockDiscordRepository
}

// NewMockDiscordRepository creates a new mock instance.
func NewMockDiscordRepository(ctrl *gomock.Controller) *MockDiscordRepository {
	mock := &MockDiscordRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordRepository) EXPECT() *MockDiscordRepositoryMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockDiscordRepository) SendMessage(ctx context.Context, channelID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockDiscordRepositoryMockRecorder) SendMessage(ctx, channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockDiscordRepository)(nil).SendMessage), ctx, channelID, content)
}

// MockDiscordMessageRepository is a mock of DiscordMessageRepository interface.
type MockDiscordMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordMessageRepositoryMockRecorder is the mock recorder for MockDiscordMessageRepository.
type MockDiscordMessageRepositoryMockRecorder struct {
	mock *MockDiscordMessageRepository
}

// NewMockDiscordMessageRepository creates a new mock instance.
func NewMockDiscordMessageRepository(ctrl *gomock.Controller) *MockDiscordMessageRepository {
	mock := &MockDiscordMessageRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordMessageRepository) EXPECT() *MockDiscordMessageRepositoryMockRecorder {
	return m.recorder
}

// SaveMessage mocks base method.
func (m *MockDiscordMessageRepository) SaveMessage(ctx context.Context, message *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockDiscordMessageRepositoryMockRecorder) SaveMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockDiscordMessageRepository)(nil).SaveMessage), ctx, message)
}

// MockLLMRepository is a mock of LLMRepository interface.
type MockLLMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMRepositoryMockRecorder
	isgomock struct{}
}

// MockLLMRepositoryMockRecorder is the mock recorder for MockLLMRepository.
type MockLLMRepositoryMockRecorder struct {
	mock *MockLLMRepository
}

// NewMockLLMRepository creates a new mock instance.
func NewMockLLMRepository(ctrl *gomock.Controller) *MockLLMRepository {
	mock := &MockLLMRepository{ctrl: ctrl}
	mock.recorder = &MockLLMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMRepository) EXPECT() *MockLLMRepositoryMockRecorder {
	return m.recorder
}

// GenerateResponse mocks base method.
func (m *MockLLMRepository) GenerateResponse(ctx context.Context, systemPrompt, userMessage string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateResponse", ctx, systemPrompt, userMessage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateResponse indicates an expected call of GenerateResponse.
func (mr *MockLLMRepositoryMockRecorder) GenerateResponse(ctx, systemPrompt, userMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateResponse", reflect.TypeOf((*MockLLMRepository)(nil).GenerateResponse), ctx, systemPrompt, userMessage)
}

// MockSystemPromptRepository is a mock of SystemPromptRepository interface.
type MockSystemPromptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemPromptRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemPromptRepositoryMockRecorder is the mock recorder for MockSystemPromptRepository.
type MockSystemPromptRepositoryMockRecorder struct {
	mock *MockSystemPromptRepository
}

// NewMockSystemPromptRepository creates a new mock instance.
func NewMockSystemPromptRepository(ctrl *gomock.Controller) *MockSystemPromptRepository {
	mock := &MockSystemPromptRepository{ctrl: ctrl}
	mock.recorder = &MockSystemPromptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemPromptRepository) EXPECT() *MockSystemPromptRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSystemPromptRepository) Get(ctx context.Context, id int) (*domain.SystemPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.SystemPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSystemPromptRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSystemPromptRepository)(nil).Get), ctx, id)
}

// MockValidationRepository is a mock of ValidationRepository interface.
type MockValidationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRepositoryMockRecorder
	isgomock struct{}
}

// MockValidationRepositoryMockRecorder is the mock recorder for MockValidationRepository.
type MockValidationRepositoryMockRecorder struct {
	mock *MockValidationRepository
}

// NewMockValidationRepository creates a new mock instance.
func NewMockValidationRepository(ctrl *gomock.Controller) *MockValidationRepository {
	mock := &MockValidationRepository{ctrl: ctrl}
	mock.recorder = &MockValidationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRepository) EXPECT() *MockValidationRepositoryMockRecorder {
	return m.recorder
}

// ShouldProcessMessage mocks base method.
func (m *MockValidationRepository) ShouldProcessMessage(message *entity.Message, botUserID string, botNameRegExp *regexp.Regexp) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessMessage", message, botUserID, botNameRegExp)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessMessage indicates an expected call of ShouldProcessMessage.
func (mr *MockValidationRepositoryMockRecorder) ShouldProcessMessage(message, botUserID, botNameRegExp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessMessage", reflect.TypeOf((*MockValidationRepository)(nil).ShouldProcessMessage), message, botUserID, botNameRegExp)
}
