name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      release-tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          release-type: simple

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    environment: deploy
    defaults:
      run:
        working-directory: ./akari
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-golang
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
      - name: Run go generate
        run: make generate
      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with ko
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
          KOSCHEME: github.com
          TAGS: "${{ needs.release-please.outputs.release-tag-name }},latest"
        run: |
          IMAGE="$(ko build --bare --tags="$TAGS" ./cmd/akari)"
          echo "Built image: ${IMAGE}"
          docker images | grep akari || true
